language: node_js
node_js:
  - "node"
  - "8"
addons:
  chrome: stable
cache: 
  yarn: true
install:
  - yarn install
  - echo 'Total node_modules dependencies:'$(ls node_modules | wc -l)
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver  
script:
  - webpack

