language: node_js
node_js: '8'
addons:
  chrome: stable
cache: yarn
install:
- yarn install
- echo 'Total node_modules dependencies:'$(ls node_modules | wc -l)
- wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
- node_modules/.bin/webpack-dev-server --hot false &
- sleep 10
- jest
- for x in $(jobs -p); do kill $x; done
- webpack
deploy:
- provider: s3
  access_key_id: AKIAJGEJ2O5VFPCQB6ZQ
  secret_access_key:
    secure: PO6dbgM+3C3l2eyUabR31GoN1xongLI8NMCXQo4JgnnWnDpT8Z5YQY+V3OFAVIUM0cMtKJ3IBymVdd4JPZWNQZJCwepcs9SMZujnyFtysJYhrUOaLgesVmcTCWHoOgAA6AbWTCEluAs28TxdfNvGak3Ss4dVYRDeKPWcMvlQjOKOCtV5TFwrsVKMUCpNC9t+dHUb9iNNU+nctOg60qrn96tBq/plAiXq84lv6OLZogKH70SVPKrofeAeQ8Bl+lYgwilIVX87TlHdB/JlllO3HNvnOSpzBanvkXJMhV3ccWuSQudcDWbVBoiMC1bifTawyCf1pz9n1y9XieiLNV64VuKwu0H2oB1f3OfrEzjtD5WWtb6R7HNq4BC7S5iC/9B6lBmnQz+EUKh006dvgFvYgdAAb5lupvzcW98j1HIesC9/HRYArpCJLZ6PHA5H+NuYNZ79j7foe9WT5DeWO9qiHIiAfDoZMyjAoUh9tYsfjylDtKfuEQ07qa1Epg9QXhcYAGJY1lmwNsf7bT2nXVq7tIQ11LiVgnPnt2vvryB+TfpnqLTo0cowUuTMedp+9w/Lu8RThR/KgNpCP5ebkyR5xA0KSONhcpr9U6G6C3GYbxIaroyG7whbroU2/UpEKeQ5qXnT3kM4PlCcpFlxIfMSybA25UXa33H8TK4/efI+KTQ=
  bucket: tyrann.asaur.us
  local-dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    branch: master
    repo: andolojm/tyrann-asaur-us
- provider: s3
  access_key_id: AKIAJGEJ2O5VFPCQB6ZQ
  secret_access_key:
    secure: PO6dbgM+3C3l2eyUabR31GoN1xongLI8NMCXQo4JgnnWnDpT8Z5YQY+V3OFAVIUM0cMtKJ3IBymVdd4JPZWNQZJCwepcs9SMZujnyFtysJYhrUOaLgesVmcTCWHoOgAA6AbWTCEluAs28TxdfNvGak3Ss4dVYRDeKPWcMvlQjOKOCtV5TFwrsVKMUCpNC9t+dHUb9iNNU+nctOg60qrn96tBq/plAiXq84lv6OLZogKH70SVPKrofeAeQ8Bl+lYgwilIVX87TlHdB/JlllO3HNvnOSpzBanvkXJMhV3ccWuSQudcDWbVBoiMC1bifTawyCf1pz9n1y9XieiLNV64VuKwu0H2oB1f3OfrEzjtD5WWtb6R7HNq4BC7S5iC/9B6lBmnQz+EUKh006dvgFvYgdAAb5lupvzcW98j1HIesC9/HRYArpCJLZ6PHA5H+NuYNZ79j7foe9WT5DeWO9qiHIiAfDoZMyjAoUh9tYsfjylDtKfuEQ07qa1Epg9QXhcYAGJY1lmwNsf7bT2nXVq7tIQ11LiVgnPnt2vvryB+TfpnqLTo0cowUuTMedp+9w/Lu8RThR/KgNpCP5ebkyR5xA0KSONhcpr9U6G6C3GYbxIaroyG7whbroU2/UpEKeQ5qXnT3kM4PlCcpFlxIfMSybA25UXa33H8TK4/efI+KTQ=
  bucket: tyrann-dev.asaur.us
  local-dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    branch: develop
    repo: andolojm/tyrann-asaur-us
